---
# file: roles/rhua/tasks/main.yml
# tasks related to rhua setup
- name: set hostname
  hostname: name=rhua.example.com
  tags: rhua

- name: install Ansible Engine
  package: name=ansible state=present
  when: ansible_engine | default(False) | bool
  tags: rhua

- name: install rhui-installer
  package: name=rhui-installer state=present
  register: install_rhui_installer
  tags: rhua

- name: call rhui-installer
  command: >
    rhui-installer
    --rhua-hostname rhua.example.com
    --cds-lb-hostname cds.example.com
    --container-support-enabled True
    --remote-fs-server nfs.example.com:/export
    {% if remote_data | default(False) %}
    --remote-fs-cert-server nfs.example.com:/rhui/certs
    --remote-fs-conf-server nfs.example.com:/rhui/conf
    --remote-fs-logs-server nfs.example.com:/rhui/logs
    {% endif %}
    {% if proxy | default(False) %}
    --proxy-hostname hap01.example.com --proxy-port 3128 --proxy-protocol http
    {% endif %}
  when: install_rhui_installer is changed
  tags: rhua

- name: check if the installed RHUI version is the latest one
  command: rpmquery --qf '%{VERSION}' rhui-tools
  register: rpmq
  failed_when: rpmq.stdout | splitext | first != latest_rhui_version
  tags: rhua,versioncheck

- name: check if the installation playbook has logged its output
  command: cat /var/log/rhui-installer/install_logger.log.latest
  register: installer_log
  failed_when: "'PLAY RECAP' not in installer_log.stdout"
  tags: rhua

- name: check if the entitlement certificate was uploaded by rhui-manager (if using RHSM)
  shell: "ls /etc/pki/rhui/redhat/*.pem"
  when: rhui_iso is undefined and credentials is defined and client_rpm is undefined

- name: check if rhui-manager can run
  command: rhui-manager --noninteractive status
  register: rhuimanagercmd
  tags: rhua

- name: print the output from rhui-manager
  debug:
    var: rhuimanagercmd.stdout

- import_tasks: ssh.yml
