---
# file: roles/rhua/tasks/main.yml
# tasks related to rhua setup
- name: set hostname
  hostname: name=rhua.example.com
  tags: rhua

- name: install Ansible Engine
  package: name=ansible state=present
  when: ansible_engine | default(False) | bool
  tags: rhua

- name: install rhui-installer
  package: name=rhui-installer state=present
  register: install_rhui_installer
  tags: rhua

- name: call rhui installer if nfs
  command: rhui-installer --rhua-hostname=rhua.example.com --remote-fs-server=nfs.example.com:/export --cds-lb-hostname cds.example.com {{ " --proxy-hostname hap01.example.com --proxy-port 3128 --proxy-protocol http" if proxy | default(False) | bool else "" }}
  when: install_rhui_installer is changed and 'NFS' in groups and groups['NFS']|length > 0
  tags: rhua

- name: check if the installed RHUI version is the latest one
  command: rpmquery --qf '%{VERSION}' rhui-tools
  register: rpmq
  failed_when: rpmq.stdout | splitext | first != latest_rhui_version
  tags: rhua,versioncheck

- name: check if the installation playbook has logged its output
  command: cat /var/log/rhui/rhui-installer/install_logger.log.latest
  register: installer_log
  failed_when: "'PLAY RECAP' not in installer_log.stdout"
  tags: rhua

- name: check if rhui-manager can run
  command: rhui-manager --noninteractive status
  register: rhuimanagercmd
  tags: rhua

- name: print the output from rhui-manager
  debug:
    var: rhuimanagercmd.stdout

- import_tasks: ssh.yml
