---
# file: roles/rhua/tasks/ssh.yml
# configure rhua--cds ssh access

- name: slurp the cds pub key
  slurp: src=/root/.ssh/id_rsa_rhua.pub
  register: slurp_id_rsa_rhua
  tags: rhua

- name: set the pub_key as a global fact
  set_fact:
    id_rsa_rhua_pub: "{{ slurp_id_rsa_rhua.content|b64decode|trim + ' rhua.example.com' }}"
  when: slurp_id_rsa_rhua is success
  tags: rhua

- name: set authorized keys on cdses and haproxy to allow ssh connections with the key
  authorized_key:
    key: "{{ hostvars[groups['RHUA'][0]]['id_rsa_rhua_pub'] }}"
    user: "{{ ansible_env.SUDO_USER }}"
    state: present
  delegate_to: "{{ item }}"
  with_items: "{{ groups['CDS']|default([]) + groups['HAPROXY']|default([]) }}"
  when: slurp_id_rsa_rhua is success
  tags: rhua
