---
# file: roles/rhui_nodes/tasks/main.yml
# repo-related tasks common to the RHUA node
# sync installation media and set up repos
# variables:
# - rhui_iso: path to the RHUI ISO to install from; if you don't supply this, be sure to supply the credentials file instead
# - rhui_iso_gpgsigs: enable/disable RHUI ISO repo gpg signature checking (default: False; see the setup_package_repos script on the ISO
# - rhsm: use RHSM instead of an ISO
# - credentials: login data for RHSM and other services, see the tests README
# - client_rpm: an alternative to the ISO or RHSM; this can be a client configuration RPM that provides e.g. scratch builds of RHUI

- name: uninstall insights
  package:
    name:
      - insights-client
      - rhc
    state: absent
  tags: rhui_nodes

- name: unregister from RHSM (the ghost subscription that would interfere with the entitlement cert)
  redhat_subscription:
    state: absent
  tags: rhui_nodes

- name: disable rhsmcertd
  service:
    name: rhsmcertd
    state: stopped
    enabled: no
  tags: rhui_nodes

- name: upload the RHUI iso
  copy:
    src: "{{ rhui_iso }}"
    dest: /tmp/rhui.iso
  register: iso_sync
  when: rhui_iso is defined
  tags: rhui_nodes

- name: mount rhui iso
  mount: name=/tmp/iso fstype=iso9660 opts=loop,ro src=/tmp/rhui.iso state=mounted
  register: iso_mount
  when: rhui_iso is defined and iso_sync is success
  tags: rhui_nodes

- name: call setup_package_repos
  command: ./setup_package_repos "{{ rhui_iso_gpgsigs|default(False)|ternary('', '--nogpgsigs') }}"
           chdir=/tmp/iso 
           creates=/etc/yum.repos.d/rhui-local.repo
  register: setup_package_repos_result
  when: rhui_iso is defined and iso_mount is success
  tags: rhui_nodes

- name: umount rhui iso
  mount: name=/tmp/iso fstype=iso9660 opts=loop,ro src=/tmp/rhui.iso state=unmounted
  when: rhui_iso is defined and iso_mount is success
  tags: rhui_nodes

- name: prevent systemd-tmpfiles from deleting the iso and the mount directory
  blockinfile:
    path: /usr/lib/tmpfiles.d/rhui_iso.conf
    block: |
      x /tmp/rhui.iso
      x /tmp/iso
    create: yes
  when: rhui_iso is defined
  tags: rhui_nodes

- name: register with RHSM
  redhat_subscription:
    state: present
    username: "{{ lookup('ini', 'username section=rh file=' + credentials) }}"
    password: "{{ lookup('ini', 'password section=rh file=' + credentials) }}"
    consumer_type: rhui
  when: rhui_iso is undefined and credentials is defined and client_rpm is undefined
  tags: rhui_nodes

- name: make sure RHSM repo management is enabled
  command: subscription-manager config --rhsm.manage_repos=1
  when: rhui_iso is undefined and credentials is defined and client_rpm is undefined
  tags: rhui_nodes

- name: enable the RHSM repos required to install RHUI 4
  rhsm_repository:
    name: rhel-8-for-x86_64-appstream-rhui-rpms,rhel-8-for-x86_64-baseos-rhui-rpms,rhui-4-for-rhel-8-x86_64-rpms
    purge: yes
  register: setup_package_repos_result
  when: rhui_iso is undefined and credentials is defined and client_rpm is undefined
  tags: rhui_nodes

- name: uninstall rh-amazon-rhui-client
  package:
    name: rh-amazon-rhui-client
    state: absent
  when: (rhui_iso is undefined and credentials is defined) or client_rpm is defined
  tags: rhui_nodes

- name: upload the supplied RHUI client RPM
  copy:
    src: "{{ client_rpm }}"
    dest: /tmp
  register: uploaded_client_rpm
  when: client_rpm is defined
  tags: rhui_nodes

- name: install the supplied RHUI client RPM
  package:
    name: "{{ uploaded_client_rpm.dest }}"
    state: present
    disable_gpg_check: yes
  when: client_rpm is defined
  tags: rhui_nodes
