---
# file: roles/haproxy/tasks/main.yml
# set up the HAProxy node; just the hostname in fact
# or, optionally, set up a proxy server (squid) for RHUA-CDN communication

- name: set hostname
  hostname: name="hap0{{ item.0 + 1 }}.example.com"
  with_indexed_items: "{{ groups['HAPROXY'] }}"
  when: "'HAPROXY' in groups and item.1 == inventory_hostname"
  tags: haproxy

- import_tasks: proxy.yml
  tags: proxy
